import Button from "@/components/ui/Button";
import { db } from "@/firebase";
import { COLLECTIONS } from "@/lib/config";
import { logout } from "@/lib/server-actions";
import { getDataFromQuerySnapshot } from "@/lib/utils";
import { collection, getDocs, query, where } from "@firebase/firestore";
import { verify } from "jsonwebtoken";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import React from "react";

export const metadata = {
  title: "My Profile - Money Maple ",
  description: "Generated by create next app",
};

async function ProfilePage() {
  const token = cookies().get("token");
  if (!token) {
    redirect("/login");
  }
  let { email, userId } = verify(token.value, process.env.NEXT_PUBLIC_JWT_SECRET);
  let usersSnapshot = await getDocs(
    query(collection(db, COLLECTIONS.USERS), where("email", "==", email))
  );
  let users = getDataFromQuerySnapshot(usersSnapshot);
  if (users.length === 0) {
    throw new Error("User not found!");
  }
  const user = users[0];
  return (
    <section className="p-5">
      <form action={logout}>
        <div className="flex flex-col gap-5 p-5 rounded-2xl bg-white shadow-lg shadow-slate-200">
          <div className="flex flex-col gap-2">
            <h2 className="text-xl font-bold text-slate-600">{`${user.firstName} ${user.lastName}`}</h2>
            <p className="text-slate-500">{user.email}</p>
          </div>
          <Button pendingLabel="Logging out...">Logout</Button>
        </div>
      </form>
    </section>
  );
}

export default ProfilePage;
